name: Análise de Código C#

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Setup do .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7

    - name: Build do Projeto
      run: dotnet build

    - name: Análise com Roslynator
      run: dotnet roslynator analyze --fix

    - name: Commit das correções
      run: git commit -a -m "Correções de código com Roslynator" || true

    - name: Push das correções
      run: git push origin main
