name: Run Roslynator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Setup do .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0

    - name: Build do Projeto
      run: dotnet build --configuration Release

    - name: Análise com Roslynator
      run: dotnet roslynator analyze --fix
      continue-on-error: true

    - name: Mostrar Sugestões
      run: |
        echo "Sugestões do Roslynator:"
        cat roslynator.log
      if: ${{ failure() }}
